//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoCategorizer.i18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoCategorizer.i18N.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign key.
        /// </summary>
        public static string AddCategoryDialog_AssignCategoryKey {
            get {
                return ResourceManager.GetString("AddCategoryDialog_AssignCategoryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned: {0}.
        /// </summary>
        public static string AddCategoryDialog_AssignedKey {
            get {
                return ResourceManager.GetString("AddCategoryDialog_AssignedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AddCategoryDialog_Ok {
            get {
                return ResourceManager.GetString("AddCategoryDialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę kategorii.
        /// </summary>
        public static string AddCategoryDialog_Text {
            get {
                return ResourceManager.GetString("AddCategoryDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj kategorię.
        /// </summary>
        public static string AddCategoryDialog_Title {
            get {
                return ResourceManager.GetString("AddCategoryDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for input....
        /// </summary>
        public static string AddCategoryDialog_WaitingForKey {
            get {
                return ResourceManager.GetString("AddCategoryDialog_WaitingForKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie pliki: {0}.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autozapis: Wyłączony.
        /// </summary>
        public static string Autosave_Off {
            get {
                return ResourceManager.GetString("Autosave_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autozapis: Włączony.
        /// </summary>
        public static string Autosave_On {
            get {
                return ResourceManager.GetString("Autosave_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. ostatni: {1}.
        /// </summary>
        public static string Autosave_Status {
            get {
                return ResourceManager.GetString("Autosave_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono {0} plików. Czy chcesz je usunąć z projektu?.
        /// </summary>
        public static string CheckMissingFilesDialog_FoundMissingFiles {
            get {
                return ResourceManager.GetString("CheckMissingFilesDialog_FoundMissingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakujące pliki.
        /// </summary>
        public static string CheckMissingFilesDialog_FoundMissingFiles_Title {
            get {
                return ResourceManager.GetString("CheckMissingFilesDialog_FoundMissingFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ErrorDialog_Close {
            get {
                return ResourceManager.GetString("ErrorDialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expected error occured :(.
        /// </summary>
        public static string ErrorDialog_Title {
            get {
                return ResourceManager.GetString("ErrorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczytanych plików: {0}.
        /// </summary>
        public static string LoadedFilesLabel {
            get {
                return ResourceManager.GetString("LoadedFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        public static string MainWindow_AddNewCategory {
            get {
                return ResourceManager.GetString("MainWindow_AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy chcesz usunąć &apos;{0}&apos;?.
        /// </summary>
        public static string RemoveCategoryDialog_Text {
            get {
                return ResourceManager.GetString("RemoveCategoryDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove category.
        /// </summary>
        public static string RemoveCategoryDialog_Title {
            get {
                return ResourceManager.GetString("RemoveCategoryDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate left.
        /// </summary>
        public static string RotateLeft {
            get {
                return ResourceManager.GetString("RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate right.
        /// </summary>
        public static string RotateRight {
            get {
                return ResourceManager.GetString("RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved in your project! Do you want to save them?.
        /// </summary>
        public static string UnsavedChangesDialog_Text {
            get {
                return ResourceManager.GetString("UnsavedChangesDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        public static string UnsavedChangesDialog_Title {
            get {
                return ResourceManager.GetString("UnsavedChangesDialog_Title", resourceCulture);
            }
        }
    }
}
