//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OuhmaniaPeopleRecognizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OuhmaniaPeopleRecognizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nazwę kategorii.
        /// </summary>
        internal static string AddCategoryDialog_Text {
            get {
                return ResourceManager.GetString("AddCategoryDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj kategorię.
        /// </summary>
        internal static string AddCategoryDialog_Title {
            get {
                return ResourceManager.GetString("AddCategoryDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie pliki: {0}.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autozapis: Wyłączony.
        /// </summary>
        internal static string Autosave_Off {
            get {
                return ResourceManager.GetString("Autosave_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autozapis: Włączony.
        /// </summary>
        internal static string Autosave_On {
            get {
                return ResourceManager.GetString("Autosave_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. ostatni: {1}.
        /// </summary>
        internal static string Autosave_Status {
            get {
                return ResourceManager.GetString("Autosave_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono {0} plików. Czy chcesz je usunąć z projektu?.
        /// </summary>
        internal static string CheckMissingFilesDialog_FoundMissingFiles {
            get {
                return ResourceManager.GetString("CheckMissingFilesDialog_FoundMissingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakujące pliki.
        /// </summary>
        internal static string CheckMissingFilesDialog_FoundMissingFiles_Title {
            get {
                return ResourceManager.GetString("CheckMissingFilesDialog_FoundMissingFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczytanych plików: {0}.
        /// </summary>
        internal static string LoadedFilesLabel {
            get {
                return ResourceManager.GetString("LoadedFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy chcesz usunąć &apos;{0}&apos;?.
        /// </summary>
        internal static string RemoveCategoryDialog_Text {
            get {
                return ResourceManager.GetString("RemoveCategoryDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń osobę.
        /// </summary>
        internal static string RemoveCategoryDialog_Title {
            get {
                return ResourceManager.GetString("RemoveCategoryDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masz niezapisane zmiany w projekcie! Czy chcesz je zapisać?.
        /// </summary>
        internal static string UnsavedChangesDialog_Text {
            get {
                return ResourceManager.GetString("UnsavedChangesDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niezapisane zmiany.
        /// </summary>
        internal static string UnsavedChangesDialog_Title {
            get {
                return ResourceManager.GetString("UnsavedChangesDialog_Title", resourceCulture);
            }
        }
    }
}
