//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OuhmaniaPeopleRecognizer.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OuhmaniaPeopleRecognizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hello Photobook.
        /// </summary>
        internal static string HelloString {
            get {
                return ResourceManager.GetString("HelloString", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wpisz imię i nazwisko.
        /// </summary>
        internal static string MainWindow_addPerson_Caption {
            get {
                return ResourceManager.GetString("MainWindow_addPerson_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj osobę.
        /// </summary>
        internal static string MainWindow_addPerson_Title {
            get {
                return ResourceManager.GetString("MainWindow_addPerson_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wszystkie pliki: {0}.
        /// </summary>
        internal static string MainWindow_allFilesCounttoolStripStatusLabel {
            get {
                return ResourceManager.GetString("MainWindow_allFilesCounttoolStripStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Autozapis: Wyłączony.
        /// </summary>
        internal static string MainWindow_Autosave_Off {
            get {
                return ResourceManager.GetString("MainWindow_Autosave_Off", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Autozapis: Włączony.
        /// </summary>
        internal static string MainWindow_Autosave_On {
            get {
                return ResourceManager.GetString("MainWindow_Autosave_On", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0}. ostatni: {1}.
        /// </summary>
        internal static string MainWindow_Autosave_Status {
            get {
                return ResourceManager.GetString("MainWindow_Autosave_Status", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono {0} plików. Czy chcesz je usunąć z projektu?.
        /// </summary>
        internal static string MainWindow_CheckMissingFiles_FoundMissingFiles {
            get {
                return ResourceManager.GetString("MainWindow_CheckMissingFiles_FoundMissingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brakujące pliki.
        /// </summary>
        internal static string MainWindow_CheckMissingFiles_FoundMissingFiles_Title {
            get {
                return ResourceManager.GetString("MainWindow_CheckMissingFiles_FoundMissingFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Masz niezapisane zmiany w projekcie! Czy chcesz je zapisać?.
        /// </summary>
        internal static string MainWindow_CheckUnsavedChangesDialog_Caption {
            get {
                return ResourceManager.GetString("MainWindow_CheckUnsavedChangesDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Niezapisane zmiany.
        /// </summary>
        internal static string MainWindow_CheckUnsavedChangesDialog_Title {
            get {
                return ResourceManager.GetString("MainWindow_CheckUnsavedChangesDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy chcesz usunąć &apos;{0}&apos;?.
        /// </summary>
        internal static string MainWindow_deletePersonToolStripContextMenuItem_Confirm {
            get {
                return ResourceManager.GetString("MainWindow_deletePersonToolStripContextMenuItem_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń osobę.
        /// </summary>
        internal static string MainWindow_deletePersonToolStripContextMenuItem_ConfirmTitle {
            get {
                return ResourceManager.GetString("MainWindow_deletePersonToolStripContextMenuItem_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wczytanych plików: {0}.
        /// </summary>
        internal static string MainWindow_loadedFilesCounttoolStripStatusLabel {
            get {
                return ResourceManager.GetString("MainWindow_loadedFilesCounttoolStripStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string MainWindow_Save {
            get {
                return ResourceManager.GetString("MainWindow_Save", resourceCulture);
            }
        }
    }
}
